all:
	pdflatex ICCAD21-Transformer-Acc.tex
	bibtex   ICCAD21-Transformer-Acc
	bibtex   ICCAD21-Transformer-Acc
	pdflatex ICCAD21-Transformer-Acc.tex
	pdflatex ICCAD21-Transformer-Acc.tex

fast:
	pdflatex ICCAD21-Transformer-Acc.tex

clean:
	rm *.log *.aux *.blg *.bbl *.gz *.dvi *.thm *.dat *.out *latexmk *fls *busy\)
